FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# hiberWare

API для вненсения изменений и получения сведений из в БД товаров.

###Сценарий работы.

API позволяет:
- Вносить изменений в список зарегистрированных товаров.
- Осуществлять закупку зарегистрированных товаров с датой и ценой закупки.
- Осуществлять продажу зарегистрированных товаров с датой и ценой продажи.
- Получать прибыль по указанному товару в конкретную дату.

## Список возможных API-запросов [/newproduct]

### Добавить товар [POST]
Указывается только наименование товара. Отметка о создании вносится в БД.

+ Request (application/json)

        {
            "name": "Лобстер"
        }
+ Response
Товар Лобстер добавлен
##Закупка товара[/purchase]
### Закупить товар [POST]

Производится закупка товара с указанием его цены, количества и даты закупки.

+ Request (application/json)

        {
    "name": "Лобстер",
    "quantity": 4,
    "buyDate": "2020-02-01",
    "buyPrice": 200
}

+ Response 200 (application/json)

    + Body
    
Товар Лобстер закуплен

+ Request (application/json)
        {
    "name": "Белорусский краб",
    "quantity": 4,
    "buyDate": "2020-02-01",
    "buyPrice": 200
}
+ Response 200 (application/json)
Данила, ты что, крейзи? Такого продукта не существует.

    + Body
##Сбыт товара[/demand]
### Продать товар [POST]

Производится закупка самого раннего из купленных (принцип FIFO) товара с указанием его цены, количества и даты закупки.

+ Request (application/json)

{
    "name": "Лобстер",
    "quantity": 3,
    "sellDate": "2020-02-02",
    "sellPrice": 800
}

+ Response 200 (application/json)

    + Body
    
Товар Лобстер реализован
##Подсчет прибыли[/revenue]
### Посчитать прибыль [GET]

Производится расчет прибыли по конкретному товару на указанную дату.

+ Request (application/json)

{
    "name": "Лобстер",
    "revenueDate": "2020-02-02"
}

+ Response 200 (application/json)

    + Body
    
Прибыль на дату 2020-02-02 составляет: 1800 рублей